language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  global:
   - secure: "VGKP/MgL+kk+DToAlMyZCN6id17oydM69yR8RC0jI9RKM73Jgsyb5iRUbP3UOpqhl/dZQB5dt14I8HMneyy7lskd+l5RNMrh5yPxM4/D9PrRhwte9xZhrDXoAi79GyRDidNhyt6g6rM3uViPe/K41c9qJy3ZY4P/t/uMq5hFKfs="
matrix:
  exclude:
    - os: osx
      compiler: gcc
before_install:
 - ./scripts/install-deps-${TRAVIS_OS_NAME}.sh
script:
 - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./scripts/ci-build.sh ; fi
addons:
  coverity_scan:
    project:
      name: "haiwen/seafile-client"
      description: "Build submitted via Travis CI"
    notification_email: rwindz0@gmail.com
    build_command_prepend: "git clean -xfd"
    build_command:   "./scripts/ci-build.sh"
    branch_pattern: coverity_scan
notifications:
  email:
    recipients:
      - linshuai2012@gmail.com
      - rwindz0@gmail.com
  slack:
    secure: RhwjY2BL0bR6MD+ASvFptH9GJmT0CshRN4YoZgK80D/H1kK60nVjfYIwU0apmhG8J3Sz9jqQ5xGPBUXvAgKB9VzdGQVgo23kGm9P2AY6xM43HHcPJvuXEBeX6zCx1O2HyGmENq36Z9ZnDWxW9yswnXKmeb05lE+PisBn1XvWQrs=
    on_success: change
    on_failure: always
